apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-mgab
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-mgab
    app.kubernetes.io/part-of: test-app-viqy
  name: test-component-mgab
  namespace: build-templates-e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-mgab
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-mgab
    spec:
      containers:
      - image: quay.io/redhat-appstudio/test-images:3619a345f1fb48279fdac7cb82809737
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
